version: "3"
services:

  postgres:
    restart: on-failure
    image: postgres
    command: [ "postgres", "-c", "port=5432", "-c", "max_locks_per_transaction=128", "-c", "shared_buffers=256MB" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oksdev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d oksdev -p 5431" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 750M
        reservations:
          cpus: "0.5"
          memory: 500M

volumes:
  postgres-data:

networks:
  custom_network:
    driver: bridge